spring:
  data:
    mongodb:
      uri: mongodb+srv://mananmehta634:mananmehta634@cluster0.7zqzbhk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
